# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

inhibit_all_warnings!
use_frameworks!

workspace 'PPHSDKSampleApp'

target 'PPHSDKSampleApp' do
    project 'PPHSDKSampleApp.xcodeproj'
    # pod 'PayPalHereSDKv2', :git=> 'git@github.paypal.com:RetailSDK-NewGen/paypal-here-sdk-ios-distribution.git', :branch => 'master'
    pod 'PayPalRetailSDK', path:'../../..' #this is the path for the rsdk. Uncomment PayPalHereSDKv2 to use the public cocoapod
end


