# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

inhibit_all_warnings!
use_frameworks!

workspace 'PPHSDKSampleApp'

target 'PPHSDKSampleApp' do
    project 'PPHSDKSampleApp.xcodeproj'
    pod 'PayPalHereSDKv2Beta', '2.1.020180101'
end


