/**
 * PPRetailAuthorizedTransaction.h
 *
 * DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED AND SHOULD NOT BE CHECKED IN.
 * Generated from: js/transaction/AuthorizedTransaction.js
 *
 * 
 */

#import "PayPalRetailSDKTypeDefs.h"
#import "PPRetailObject.h"


@class PPRetailSDK;
@class PPRetailError;
@class PPRetailPayPalErrorInfo;
@class PPRetailAccountSummary;
@class PPRetailAccountSummarySection;
@class PPRetailInvoiceAddress;
@class PPRetailInvoiceAttachment;
@class PPRetailInvoiceBillingInfo;
@class PPRetailInvoiceCCInfo;
@class PPRetailCountries;
@class PPRetailCountry;
@class PPRetailInvoiceCustomAmount;
@class PPRetailInvoice;
@class PPRetailInvoiceActions;
@class PPRetailInvoiceConstants;
@class PPRetailInvoiceListRequest;
@class PPRetailInvoiceListResponse;
@class PPRetailInvoiceMetaData;
@class PPRetailInvoiceTemplatesResponse;
@class PPRetailInvoicingService;
@class PPRetailInvoiceItem;
@class PPRetailInvoiceMerchantInfo;
@class PPRetailInvoiceNotification;
@class PPRetailInvoicePayment;
@class PPRetailInvoicePaymentTerm;
@class PPRetailInvoiceRefund;
@class PPRetailInvoiceSearchRequest;
@class PPRetailInvoiceShippingInfo;
@class PPRetailInvoiceTemplate;
@class PPRetailInvoiceTemplateSettings;
@class PPRetailMerchant;
@class PPRetailNetworkRequest;
@class PPRetailNetworkResponse;
@class PPRetailSdkEnvironmentInfo;
@class PPRetailRetailInvoice;
@class PPRetailRetailInvoicePayment;
@class PPRetailTokenExpirationHandler;
@class PPRetailCaptureHandler;
@class PPRetailTransactionContext;
@class PPRetailTransactionManager;
@class PPRetailTransactionBeginOptions;
@class PPRetailReceiptDestination;
@class PPRetailDeviceManager;
@class PPRetailSignatureReceiver;
@class PPRetailReceiptOptionsViewContent;
@class PPRetailReceiptEmailEntryViewContent;
@class PPRetailReceiptSMSEntryViewContent;
@class PPRetailReceiptViewContent;
@class PPRetailCard;
@class PPRetailBatteryInfo;
@class PPRetailMagneticCard;
@class PPRetailPaymentDevice;
@class PPRetailManuallyEnteredCard;
@class PPRetailDeviceUpdate;
@class PPRetailCardInsertedHandler;
@class PPRetailDeviceStatus;
@class PPRetailPayer;
@class PPRetailTransactionRecord;
@class PPRetailAuthorizedTransaction;
@class PPRetailPage;
@class PPRetailDiscoveredCardReader;
@class PPRetailCardReaderScanAndDiscoverOptions;
@class PPRetailDeviceConnectorOptions;


/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/
/**
 * Information about a completed capture
 */
@interface PPRetailAuthorizedTransaction : PPRetailObject

    /**
    * The PayPal transaction reference number for this authorization @readonly
    */
    @property (nonatomic,strong,nullable,readonly) NSString* authorizationId;
    /**
    * The PayPal invoice id for this authorization @readonly
    */
    @property (nonatomic,strong,nullable,readonly) NSString* invoiceId;
    /**
    * Time at which this authorization activity was created
    */
    @property (nonatomic,strong,nullable) NSDate* timeCreated;
    /**
    * Amount authorized for this transaction
    */
    @property (nonatomic,strong,nullable) NSDecimalNumber* authorizedAmount;
    /**
    * Currency in which the net amount was authorized @readonly
    */
    @property (nonatomic,strong,nullable,readonly) NSString* currency;
    /**
    * Status of the current authorization
    */
    @property (nonatomic,strong,nullable) NSString* status;


    
      - (instancetype _Nullable)initWithAuthorizationId:(NSString* _Nullable)authorizationId invoiceId:(NSString* _Nullable)invoiceId currency:(NSString* _Nullable)currency;
      
    - (instancetype _Null_unspecified)init NS_UNAVAILABLE;
    + (instancetype _Null_unspecified)new NS_UNAVAILABLE;




    /**
     * Void this authorized transaction
     */
    -(void)voidTransaction:(PPRetailAuthorizedTransactionVoidCompleteHandler _Nullable)callback;

    /**
     * Capture this authorized transaction
     */
    -(void)captureTransaction:(NSDecimalNumber* _Nullable)totalAmount gratuityAmount:(NSDecimalNumber* _Nullable)gratuityAmount callback:(PPRetailAuthorizedTransactionCaptureCompleteHandler _Nullable)callback;

    /**
     * Capture this authorized transaction
     */
    -(void)captureTransaction:(NSDecimalNumber* _Nullable)totalAmount gratuityAmount:(NSDecimalNumber* _Nullable)gratuityAmount base64SignatureJpeg:(NSString* _Nullable)base64SignatureJpeg callback:(PPRetailAuthorizedTransactionCaptureCompleteHandler _Nullable)callback;




@end
