/**
 * PPRetailInvoicePayment.h
 *
 * DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED AND SHOULD NOT BE CHECKED IN.
 * Generated from: node_modules/paypal-invoicing/lib/Payment.js
 *
 * 
 */

#import "PayPalRetailSDKTypeDefs.h"
#import "PPRetailObject.h"


@class PPRetailSDK;
@class PPRetailError;
@class PPRetailPayPalErrorInfo;
@class PPRetailAccountSummary;
@class PPRetailAccountSummarySection;
@class PPRetailInvoiceAddress;
@class PPRetailInvoiceAttachment;
@class PPRetailInvoiceBillingInfo;
@class PPRetailInvoiceCCInfo;
@class PPRetailCountries;
@class PPRetailCountry;
@class PPRetailInvoiceCustomAmount;
@class PPRetailInvoice;
@class PPRetailInvoiceActions;
@class PPRetailInvoiceConstants;
@class PPRetailInvoiceListRequest;
@class PPRetailInvoiceListResponse;
@class PPRetailInvoiceMetaData;
@class PPRetailInvoiceTemplatesResponse;
@class PPRetailInvoicingService;
@class PPRetailInvoiceItem;
@class PPRetailInvoiceMerchantInfo;
@class PPRetailInvoiceNotification;
@class PPRetailInvoicePayment;
@class PPRetailInvoicePaymentTerm;
@class PPRetailInvoiceRefund;
@class PPRetailInvoiceSearchRequest;
@class PPRetailInvoiceShippingInfo;
@class PPRetailInvoiceTemplate;
@class PPRetailInvoiceTemplateSettings;
@class PPRetailMerchant;
@class PPRetailNetworkRequest;
@class PPRetailNetworkResponse;
@class PPRetailSdkEnvironmentInfo;
@class PPRetailRetailInvoice;
@class PPRetailRetailInvoicePayment;
@class PPRetailTokenExpirationHandler;
@class PPRetailCaptureHandler;
@class PPRetailTransactionContext;
@class PPRetailTransactionManager;
@class PPRetailTransactionBeginOptions;
@class PPRetailReceiptDestination;
@class PPRetailDeviceManager;
@class PPRetailSignatureReceiver;
@class PPRetailReceiptOptionsViewContent;
@class PPRetailReceiptEmailEntryViewContent;
@class PPRetailReceiptSMSEntryViewContent;
@class PPRetailReceiptViewContent;
@class PPRetailCard;
@class PPRetailBatteryInfo;
@class PPRetailMagneticCard;
@class PPRetailPaymentDevice;
@class PPRetailManuallyEnteredCard;
@class PPRetailDeviceUpdate;
@class PPRetailCardInsertedHandler;
@class PPRetailDeviceStatus;
@class PPRetailPayer;
@class PPRetailTransactionRecord;
@class PPRetailAuthorizedTransaction;
@class PPRetailPage;
@class PPRetailDiscoveredCardReader;
@class PPRetailCardReaderScanAndDiscoverOptions;
@class PPRetailDeviceConnectorOptions;


/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/
/**
 * Container for information about the payment on an invoice
 */
@interface PPRetailInvoicePayment : PPRetailObject

    /**
    * PayPal payment detail indicating whether
 * payment was made in an invoicing flow via PayPal or externally. @readonly
    */
    @property (nonatomic,assign,readonly) PPRetailInvoicePaymentType type;
    /**
    * PayPal payment transaction id. Mandatory
 * field in case the type value is PAYPAL. @readonly
    */
    @property (nonatomic,strong,nullable,readonly) NSString* transactionID;
    /**
    * type of the transaction @readonly
    */
    @property (nonatomic,strong,nullable,readonly) NSString* transactionType;
    /**
    * date when the invoice was paid
    */
    @property (nonatomic,strong,nullable) NSDate* date;
    /**
    * date, formatted in MMM, D YYYY format
    */
    @property (nonatomic,strong,nullable) NSString* formattedDate;
    /**
    * payment mode or method this is mandatory
    */
    @property (nonatomic,assign) PPRetailInvoicePaymentMethod method;
    /**
    * optional note associated with the payment
    */
    @property (nonatomic,strong,nullable) NSString* note;
    /**
    * this is an amount object on the server which
 * has a string for currency, and value
    */
    @property (nonatomic,strong,nullable) NSDecimalNumber* amount;
    /**
    * used with the amount
    */
    @property (nonatomic,strong,nullable) NSString* currency;








@end
