/**
 * PPRetailInvoiceBillingInfo.h
 *
 * DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED AND SHOULD NOT BE CHECKED IN.
 * Generated from: node_modules/paypal-invoicing/lib/BillingInfo.js
 *
 * 
 */

#import "PayPalRetailSDKTypeDefs.h"
#import "PPRetailObject.h"

@class PPRetailSDK;
@class PPRetailError;
@class PPRetailAccountSummary;
@class PPRetailAccountSummarySection;
@class PPRetailInvoiceAddress;
@class PPRetailInvoiceAttachment;
@class PPRetailInvoiceBillingInfo;
@class PPRetailInvoiceCCInfo;
@class PPRetailCountries;
@class PPRetailCountry;
@class PPRetailInvoice;
@class PPRetailInvoiceActions;
@class PPRetailInvoiceListRequest;
@class PPRetailInvoiceListResponse;
@class PPRetailInvoiceTemplatesResponse;
@class PPRetailInvoicingService;
@class PPRetailInvoiceItem;
@class PPRetailInvoiceMerchantInfo;
@class PPRetailInvoiceNotification;
@class PPRetailInvoicePayment;
@class PPRetailInvoicePaymentInfo;
@class PPRetailInvoicePaymentTerm;
@class PPRetailInvoiceRefund;
@class PPRetailInvoiceRefundInfo;
@class PPRetailInvoiceSearchRequest;
@class PPRetailInvoiceShippingInfo;
@class PPRetailInvoiceTemplate;
@class PPRetailMerchant;
@class PPRetailTransactionContext;
@class PPRetailSignatureReceiver;
@class PPRetailCard;
@class PPRetailBatteryInfo;
@class PPRetailMagneticCard;
@class PPRetailPaymentDevice;
@class PPRetailEmvDevice;
@class PPRetailDeviceUpdate;
@class PPRetailDeviceOperationResultHandler;
@class PPRetailVirtualPaymentDevice;
@class PPRetailPayer;
@class PPRetailTransactionRecord;

/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/
/**
 * Container for information about the payer or intended payer on an invoice
 */
@interface PPRetailInvoiceBillingInfo : PPRetailObject

    /**
    * The email address of the payer @required @length(1,260) @format(email)
    */
    @property (nonatomic,strong) NSString* email;
    /**
    * The first name of the payer @length(,30)
    */
    @property (nonatomic,strong) NSString* firstName;
    /**
    * The last name of the payer @length(,30)
    */
    @property (nonatomic,strong) NSString* lastName;
    /**
    * The business name of the payer
    */
    @property (nonatomic,strong) NSString* businessName;
    /**
    * The address of the payer @length(,100)
    */
    @property (nonatomic,strong) PPRetailInvoiceAddress* address;
    /**
    * Language of the email sent to the payer. Will only be used if payer doesn't have a PayPal account.
    */
    @property (nonatomic,strong) NSString* language;
    /**
    * Option to display additional information such as business hours. 40 characters max.
    */
    @property (nonatomic,strong) NSString* additionalInfo;
    /**
    * Preferred notification channel of the payer. Email by default.
    */
    @property (nonatomic,strong) NSString* notificationChannel;
    /**
    * Country code (in E.164 format). Assume length is n.
    */
    @property (nonatomic,strong) NSString* countryCode;
    /**
    * In-country phone number (in E.164 format). Maximum (15 - n) digits
    */
    @property (nonatomic,strong) NSString* nationalNumber;





    /**
     * Check to see if this object has any value
     */
    -(BOOL)hasAnyValue;




@end
