/**
 * PPRetailDeviceUpdate.h
 *
 * DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED AND SHOULD NOT BE CHECKED IN.
 * Generated from: js/paymentDevice/DeviceUpdate.js
 *
 * 
 */

#import "PayPalRetailSDKTypeDefs.h"
#import "PPRetailObject.h"

@class PPRetailSDK;
@class PPRetailError;
@class PPRetailAccountSummary;
@class PPRetailAccountSummarySection;
@class PPRetailInvoiceAddress;
@class PPRetailInvoiceAttachment;
@class PPRetailInvoiceBillingInfo;
@class PPRetailInvoiceCCInfo;
@class PPRetailCountries;
@class PPRetailCountry;
@class PPRetailInvoice;
@class PPRetailInvoiceActions;
@class PPRetailInvoiceListRequest;
@class PPRetailInvoiceListResponse;
@class PPRetailInvoiceTemplatesResponse;
@class PPRetailInvoicingService;
@class PPRetailInvoiceItem;
@class PPRetailInvoiceMerchantInfo;
@class PPRetailInvoiceNotification;
@class PPRetailInvoicePayment;
@class PPRetailInvoicePaymentInfo;
@class PPRetailInvoicePaymentTerm;
@class PPRetailInvoiceRefund;
@class PPRetailInvoiceRefundInfo;
@class PPRetailInvoiceSearchRequest;
@class PPRetailInvoiceShippingInfo;
@class PPRetailInvoiceTemplate;
@class PPRetailMerchant;
@class PPRetailTransactionContext;
@class PPRetailSignatureReceiver;
@class PPRetailCard;
@class PPRetailBatteryInfo;
@class PPRetailMagneticCard;
@class PPRetailPaymentDevice;
@class PPRetailEmvDevice;
@class PPRetailDeviceUpdate;
@class PPRetailDeviceOperationResultHandler;
@class PPRetailVirtualPaymentDevice;
@class PPRetailPayer;
@class PPRetailTransactionRecord;

/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/
/**
 * A device update object is passed to your application via the PaymentDevice#updateRequired event and is capable
 * of applying an update to a device.
 */
@interface PPRetailDeviceUpdate : PPRetailObject

    /**
    * Whether the update is required before taking further transactions using the device
    */
    @property (nonatomic,assign) BOOL isRequired;

    -(instancetype)initWithDevice:(PPRetailPaymentDevice*)device;
    - (instancetype)init NS_UNAVAILABLE;
    + (instancetype)new NS_UNAVAILABLE;




    /**
     * Display a prompt to the merchant offering the opportunity to upgrade the payment device, and optionally
     * update the device. Call the callback with completion status when the upgrade is complete or cancelled.
     */
    -(void)offer:(PPRetailDeviceUpdateCompletedHandler)callback;

    /**
     * Begin the software update.
     */
    -(void)begin:(BOOL)displayUI callback:(PPRetailDeviceUpdateCompletedHandler)callback;




    /**
     * Add a listener for the reconnectReader event
     * @returns PPRetailReconnectReaderSignal an object that can be used to remove the listener when
     * you're done with it.
     */
    -(PPRetailReconnectReaderSignal)addReconnectReaderListener:(PPRetailReconnectReaderEvent)listener;

    /**
     * Remove a listener for the reconnectReader event given the signal object that was returned from addReconnectReaderListener
     */
    -(void)removeReconnectReaderListener:(PPRetailReconnectReaderSignal)listenerToken;


@end
