/**
 * PPRetailInvoiceSearchRequest.h
 *
 * DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED AND SHOULD NOT BE CHECKED IN.
 * Generated from: node_modules/paypal-invoicing/lib/SearchRequest.js
 *
 * 
 */

#import "PayPalRetailSDKTypeDefs.h"
#import "PPRetailObject.h"

@class PPRetailSDK;
@class PPRetailError;
@class PPRetailAccountSummary;
@class PPRetailAccountSummarySection;
@class PPRetailInvoiceAddress;
@class PPRetailInvoiceAttachment;
@class PPRetailInvoiceBillingInfo;
@class PPRetailInvoiceCCInfo;
@class PPRetailCountries;
@class PPRetailCountry;
@class PPRetailInvoice;
@class PPRetailInvoiceActions;
@class PPRetailInvoiceListRequest;
@class PPRetailInvoiceListResponse;
@class PPRetailInvoiceTemplatesResponse;
@class PPRetailInvoicingService;
@class PPRetailInvoiceItem;
@class PPRetailInvoiceMerchantInfo;
@class PPRetailInvoiceNotification;
@class PPRetailInvoicePayment;
@class PPRetailInvoicePaymentInfo;
@class PPRetailInvoicePaymentTerm;
@class PPRetailInvoiceRefund;
@class PPRetailInvoiceRefundInfo;
@class PPRetailInvoiceSearchRequest;
@class PPRetailInvoiceShippingInfo;
@class PPRetailInvoiceTemplate;
@class PPRetailMerchant;
@class PPRetailTransactionContext;
@class PPRetailSignatureReceiver;
@class PPRetailCard;
@class PPRetailBatteryInfo;
@class PPRetailMagneticCard;
@class PPRetailPaymentDevice;
@class PPRetailEmvDevice;
@class PPRetailDeviceUpdate;
@class PPRetailDeviceOperationResultHandler;
@class PPRetailVirtualPaymentDevice;
@class PPRetailPayer;
@class PPRetailTransactionRecord;

/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/
/**
 * 
 */
@interface PPRetailInvoiceSearchRequest : PPRetailObject

    /**
    * Initial letters of the email address.
    */
    @property (nonatomic,strong) NSString* email;
    /**
    * Initial letters of the recipient's first name.
    */
    @property (nonatomic,strong) NSString* recipientFirstName;
    /**
    * Initial letters of the recipient's last name.
    */
    @property (nonatomic,strong) NSString* recipientLastName;
    /**
    * Initial letters of the recipient's business name.
    */
    @property (nonatomic,strong) NSString* recipientBusinessName;
    /**
    * The invoice number that appears on the invoice.
    */
    @property (nonatomic,strong) NSString* number;
    /**
    * Base object for all financial value related fields (balance, payment due, etc.)
    */
    @property (nonatomic,strong) NSDecimalNumber* lowerTotalAmount;
    /**
    * Base object for all financial value related fields (balance, payment due, etc.)
    */
    @property (nonatomic,strong) NSDecimalNumber* upperTotalAmount;
    /**
    * Start invoice date. Date format yyyy-MM-dd z, as defined in ISO8601.
    */
    @property (nonatomic,strong) NSDate* startInvoiceDate;
    /**
    * End invoice date. Date format yyyy-MM-dd z, as defined in ISO8601.
    */
    @property (nonatomic,strong) NSDate* endInvoiceDate;
    /**
    * Start invoice due date. Date format yyyy-MM-dd z, as defined in ISO8601.
    */
    @property (nonatomic,strong) NSDate* startDueDate;
    /**
    * End invoice due date. Date format yyyy-MM-dd z, as defined in ISO8601.
    */
    @property (nonatomic,strong) NSDate* endDueDate;
    /**
    * Start invoice payment date. Date format yyyy-MM-dd z, as defined in ISO8601.
    */
    @property (nonatomic,strong) NSDate* startPaymentDate;
    /**
    * End invoice payment date. Date format yyyy-MM-dd z, as defined in ISO8601.
    */
    @property (nonatomic,strong) NSDate* endPaymentDate;
    /**
    * Start invoice creation date. Date format yyyy-MM-dd z, as defined in ISO8601.
    */
    @property (nonatomic,strong) NSDate* startCreationDate;
    /**
    * End invoice creation date. Date format yyyy-MM-dd z, as defined in ISO8601.
    */
    @property (nonatomic,strong) NSDate* endCreationDate;
    /**
    * A zero-relative index of the merchant's list of invoices
    */
    @property (nonatomic,assign) int startIndex;
    /**
    * Page size of the search results.
    */
    @property (nonatomic,assign) int pageSize;
    /**
    * A flag indicating whether total count is required in the response.
    */
    @property (nonatomic,assign) BOOL totalCountRequired;
    /**
    * A flag indicating whether search is on invoices archived by merchant. true - returns archived / false returns unarchived / null returns all.
    */
    @property (nonatomic,assign) BOOL archived;





    /**
     * Manticore doesn't support properties that are arrays of enum values, and it's complicated.
     * So instead of a property for the status array, we have this method.
     */
    -(void)addStatus:(PPRetailInvoiceStatus)status;




@end
