/**
 * PPRetailInvoicePaymentInfo.h
 *
 * DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED AND SHOULD NOT BE CHECKED IN.
 * Generated from: node_modules/paypal-invoicing/lib/PaymentInfo.js
 *
 * 
 */

#import "PayPalRetailSDKTypeDefs.h"
#import "PPRetailObject.h"

@class PPRetailSDK;
@class PPRetailError;
@class PPRetailAccountSummary;
@class PPRetailAccountSummarySection;
@class PPRetailInvoiceAddress;
@class PPRetailInvoiceAttachment;
@class PPRetailInvoiceBillingInfo;
@class PPRetailInvoiceCCInfo;
@class PPRetailCountries;
@class PPRetailCountry;
@class PPRetailInvoice;
@class PPRetailInvoiceActions;
@class PPRetailInvoiceListRequest;
@class PPRetailInvoiceListResponse;
@class PPRetailInvoiceTemplatesResponse;
@class PPRetailInvoicingService;
@class PPRetailInvoiceItem;
@class PPRetailInvoiceMerchantInfo;
@class PPRetailInvoiceNotification;
@class PPRetailInvoicePayment;
@class PPRetailInvoicePaymentInfo;
@class PPRetailInvoicePaymentTerm;
@class PPRetailInvoiceRefund;
@class PPRetailInvoiceRefundInfo;
@class PPRetailInvoiceSearchRequest;
@class PPRetailInvoiceShippingInfo;
@class PPRetailInvoiceTemplate;
@class PPRetailMerchant;
@class PPRetailTransactionContext;
@class PPRetailSignatureReceiver;
@class PPRetailCard;
@class PPRetailBatteryInfo;
@class PPRetailMagneticCard;
@class PPRetailPaymentDevice;
@class PPRetailEmvDevice;
@class PPRetailDeviceUpdate;
@class PPRetailDeviceOperationResultHandler;
@class PPRetailVirtualPaymentDevice;
@class PPRetailPayer;
@class PPRetailTransactionRecord;

/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/
/**
 * Invoicing payment information
 */
@interface PPRetailInvoicePaymentInfo : PPRetailObject

    @property (nonatomic,assign) PPRetailInvoicePaymentType type;
    /**
    * PayPal payment transaction id. Mandatory field in case the type value is PAYPAL.
    */
    @property (nonatomic,strong) NSString* transactionId;
    /**
    * Type of the transaction.
    */
    @property (nonatomic,strong) NSString* transactionType;
    /**
    * Date when the invoice was paid.
    */
    @property (nonatomic,strong) NSDate* date;
    /**
    * Payment mode or method. This field is mandatory if the value of the type field is EXTERNAL.
    */
    @property (nonatomic,assign) PPRetailInvoicePaymentMethod method;
    /**
    * Optional note associated with the payment.
    */
    @property (nonatomic,strong) NSString* note;
    /**
    * this is an amount object on the server which has a string for currency, and value
    */
    @property (nonatomic,strong) NSDecimalNumber* amount;
    /**
    * used with the amount
    */
    @property (nonatomic,strong) NSString* currency;








@end
