/**
 * PPRetailEmvDevice.h
 *
 * DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED AND SHOULD NOT BE CHECKED IN.
 * Generated from: node_modules/retail-payment-device/lib/EmvDevice.js
 *
 * 
 */

#import "PayPalRetailSDKTypeDefs.h"
#import "PPRetailObject.h"

@class PPRetailSDK;
@class PPRetailError;
@class PPRetailAccountSummary;
@class PPRetailAccountSummarySection;
@class PPRetailInvoiceAddress;
@class PPRetailInvoiceAttachment;
@class PPRetailInvoiceBillingInfo;
@class PPRetailInvoiceCCInfo;
@class PPRetailCountries;
@class PPRetailCountry;
@class PPRetailInvoice;
@class PPRetailInvoiceActions;
@class PPRetailInvoiceListRequest;
@class PPRetailInvoiceListResponse;
@class PPRetailInvoiceTemplatesResponse;
@class PPRetailInvoicingService;
@class PPRetailInvoiceItem;
@class PPRetailInvoiceMerchantInfo;
@class PPRetailInvoiceNotification;
@class PPRetailInvoicePayment;
@class PPRetailInvoicePaymentInfo;
@class PPRetailInvoicePaymentTerm;
@class PPRetailInvoiceRefund;
@class PPRetailInvoiceRefundInfo;
@class PPRetailInvoiceSearchRequest;
@class PPRetailInvoiceShippingInfo;
@class PPRetailInvoiceTemplate;
@class PPRetailMerchant;
@class PPRetailTransactionContext;
@class PPRetailSignatureReceiver;
@class PPRetailCard;
@class PPRetailBatteryInfo;
@class PPRetailMagneticCard;
@class PPRetailPaymentDevice;
@class PPRetailEmvDevice;
@class PPRetailDeviceUpdate;
@class PPRetailDeviceOperationResultHandler;
@class PPRetailVirtualPaymentDevice;
@class PPRetailPayer;
@class PPRetailTransactionRecord;

/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/
/**
 * Represents an EMV reader which may support contact and/or contactless
 * payments, swipes, PIN entry and more.
 */
@interface PPRetailEmvDevice : PPRetailObject

    /**
    * The current state of the EMV card reader @readonly
    */
    @property (nonatomic,assign,readonly) PPRetailEmvDeviceCardStatus cardStatus;





    /**
     * Prompt for a non-secure amount or numeric value to be entered.
     */
    -(void)promptForNumericEntry:(NSString*)promptIndexes numberFormat:(NSString*)numberFormat numberToEdit:(NSString*)numberToEdit callback:(PPRetailEmvDeviceAmountEnteredHandler)callback;

    /**
     * Get a secure Personal Account Number (PAN) from the device
     */
    -(void)promptForSecureAccountNumber:(NSString*)promptIndexes callback:(PPRetailEmvDeviceSecureEntryHandler)callback;




@end
