/**
 * PPRetailInvoicePayment.h
 *
 * DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED AND SHOULD NOT BE CHECKED IN.
 * Generated from: node_modules/paypal-invoicing/lib/Payment.js
 *
 * 
 */

#import "PayPalRetailSDKTypeDefs.h"
#import "PPRetailObject.h"

@class PPRetailSDK;
@class PPRetailError;
@class PPRetailAccountSummary;
@class PPRetailAccountSummarySection;
@class PPRetailInvoiceAddress;
@class PPRetailInvoiceAttachment;
@class PPRetailInvoiceBillingInfo;
@class PPRetailInvoiceCCInfo;
@class PPRetailCountries;
@class PPRetailCountry;
@class PPRetailInvoice;
@class PPRetailInvoiceActions;
@class PPRetailInvoiceListRequest;
@class PPRetailInvoiceListResponse;
@class PPRetailInvoiceTemplatesResponse;
@class PPRetailInvoicingService;
@class PPRetailInvoiceItem;
@class PPRetailInvoiceMerchantInfo;
@class PPRetailInvoiceNotification;
@class PPRetailInvoicePayment;
@class PPRetailInvoicePaymentInfo;
@class PPRetailInvoicePaymentTerm;
@class PPRetailInvoiceRefund;
@class PPRetailInvoiceRefundInfo;
@class PPRetailInvoiceSearchRequest;
@class PPRetailInvoiceShippingInfo;
@class PPRetailInvoiceTemplate;
@class PPRetailMerchant;
@class PPRetailTransactionContext;
@class PPRetailSignatureReceiver;
@class PPRetailCard;
@class PPRetailBatteryInfo;
@class PPRetailMagneticCard;
@class PPRetailPaymentDevice;
@class PPRetailEmvDevice;
@class PPRetailDeviceUpdate;
@class PPRetailDeviceOperationResultHandler;
@class PPRetailVirtualPaymentDevice;
@class PPRetailPayer;
@class PPRetailTransactionRecord;

/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/
/**
 * Container for information about the payment on an invoice
 */
@interface PPRetailInvoicePayment : PPRetailObject

    /**
    * PayPal payment detail indicating whether payment was made in an invoicing flow via PayPal or externally. @readonly
    */
    @property (nonatomic,strong,readonly) NSString* type;
    /**
    * PayPal payment transaction id. Mandatory field in case the type value is PAYPAL. @readonly
    */
    @property (nonatomic,strong,readonly) NSString* transactionID;
    /**
    * type of the transaction @readonly
    */
    @property (nonatomic,strong,readonly) NSString* transactionType;
    /**
    * date when the invoice was paid
    */
    @property (nonatomic,strong) NSDate* date;
    /**
    * payment mode or method this is mandatory
    */
    @property (nonatomic,strong) NSString* method;
    /**
    * optional note associated with the payment
    */
    @property (nonatomic,strong) NSString* note;
    /**
    * this is an amount object on the server which has a string for currency, and value
    */
    @property (nonatomic,strong) NSDecimalNumber* amount;
    /**
    * used with the amount
    */
    @property (nonatomic,strong) NSString* currency;








@end
