/**
 * PPRetailInvoiceItem.h
 *
 * DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED AND SHOULD NOT BE CHECKED IN.
 * Generated from: node_modules/paypal-invoicing/lib/Item.js
 *
 * 
 */

#import "PayPalRetailSDKTypeDefs.h"
#import "PPRetailObject.h"


@class PPRetailSDK;
@class PPRetailError;
@class PPRetailPayPalErrorInfo;
@class PPRetailAccountSummary;
@class PPRetailAccountSummarySection;
@class PPRetailInvoiceAddress;
@class PPRetailInvoiceAttachment;
@class PPRetailInvoiceBillingInfo;
@class PPRetailInvoiceCCInfo;
@class PPRetailCountries;
@class PPRetailCountry;
@class PPRetailInvoiceCustomAmount;
@class PPRetailInvoice;
@class PPRetailInvoiceActions;
@class PPRetailInvoiceConstants;
@class PPRetailInvoiceListRequest;
@class PPRetailInvoiceListResponse;
@class PPRetailInvoiceMetaData;
@class PPRetailInvoiceTemplatesResponse;
@class PPRetailInvoicingService;
@class PPRetailInvoiceItem;
@class PPRetailInvoiceMerchantInfo;
@class PPRetailInvoiceNotification;
@class PPRetailInvoicePayment;
@class PPRetailInvoicePaymentTerm;
@class PPRetailInvoiceRefund;
@class PPRetailInvoiceSearchRequest;
@class PPRetailInvoiceShippingInfo;
@class PPRetailInvoiceTemplate;
@class PPRetailInvoiceTemplateSettings;
@class PPRetailMerchant;
@class PPRetailNetworkRequest;
@class PPRetailNetworkResponse;
@class PPRetailSdkEnvironmentInfo;
@class PPRetailRetailInvoice;
@class PPRetailRetailInvoicePayment;
@class PPRetailTokenExpirationHandler;
@class PPRetailCaptureHandler;
@class PPRetailTransactionContext;
@class PPRetailTransactionManager;
@class PPRetailTransactionBeginOptions;
@class PPRetailReceiptDestination;
@class PPRetailDeviceManager;
@class PPRetailSignatureReceiver;
@class PPRetailReceiptOptionsViewContent;
@class PPRetailReceiptEmailEntryViewContent;
@class PPRetailReceiptSMSEntryViewContent;
@class PPRetailReceiptViewContent;
@class PPRetailCard;
@class PPRetailBatteryInfo;
@class PPRetailMagneticCard;
@class PPRetailPaymentDevice;
@class PPRetailManuallyEnteredCard;
@class PPRetailDeviceUpdate;
@class PPRetailCardInsertedHandler;
@class PPRetailDeviceStatus;
@class PPRetailPayer;
@class PPRetailTransactionRecord;
@class PPRetailAuthorizedTransaction;
@class PPRetailPage;
@class PPRetailDiscoveredCardReader;
@class PPRetailCardReaderScanAndDiscoverOptions;
@class PPRetailDeviceConnectorOptions;


/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/
/**
 * A line item on an invoice. Can be positive, negative, or zero total/unit price.
 * See https://cms.paypal.com/cms_content/US/en_US/files/developer/PP_InvoicingAPIGuide.pdf
 * for details on field length restrictions and formats.
 */
@interface PPRetailInvoiceItem : PPRetailObject

    /**
    * The name of this item
    */
    @property (nonatomic,strong,nullable) NSString* name;
    /**
    * A description for this line item
    */
    @property (nonatomic,strong,nullable) NSString* itemDescription;
    /**
    * The quantity of this item - up to three decimals
    */
    @property (nonatomic,strong,nullable) NSDecimalNumber* quantity;
    /**
    * The price of 1 unit of this item
    */
    @property (nonatomic,strong,nullable) NSDecimalNumber* unitPrice;
    /**
    * A unique identifier for this item - not currently saved to the
 * server but used for local uniqueness such that one line item per itemId.detailId pair
 * will be stored on an invoice @readonly
    */
    @property (nonatomic,assign,readonly) int itemId;
    /**
    * A secondary unique identifier (e.g. for item options
 * or sizes, or to create multiple items on the same invoice with a single detailId) @readonly
    */
    @property (nonatomic,strong,nullable,readonly) NSString* detailId;
    /**
    * The name for the tax rate applied to this item, if any
    */
    @property (nonatomic,strong,nullable) NSString* taxName;
    /**
    * The tax rate to be applied to this item. If non-zero,
 * the taxName must also be set.
    */
    @property (nonatomic,strong,nullable) NSDecimalNumber* taxRate;
    /**
    * A percentage discount for this line item
    */
    @property (nonatomic,strong,nullable) NSDecimalNumber* discountPercentage;
    /**
    * A flat amount discount for this line item
    */
    @property (nonatomic,strong,nullable) NSDecimalNumber* discountAmount;
    /**
    * Date on which the item or service was provided
    */
    @property (nonatomic,strong,nullable) NSDate* date;
    /**
    * Image url of the item. 4000 characters max.
    */
    @property (nonatomic,strong,nullable) NSString* imageURL;
    /**
    * Unit of measure of the item being invoiced.
    */
    @property (nonatomic,strong,nullable) NSString* unitOfMeasure;


    
      - (instancetype _Nullable)initWithName:(NSString* _Nullable)name quantity:(NSDecimalNumber* _Nullable)quantity unitPrice:(NSDecimalNumber* _Nullable)unitPrice itemId:(int)itemId detailId:(NSString* _Nullable)detailId;
      
    - (instancetype _Null_unspecified)init NS_UNAVAILABLE;
    + (instancetype _Null_unspecified)new NS_UNAVAILABLE;




    /**
     * Create a true copy / duplicate of an item. This is named duplicate instead
     * of copy to avoid code gen issues on iOS
     */
    -(PPRetailInvoiceItem* _Nullable)duplicate;

    /**
     * Returns a decimal for the discount amount for this item, regardless of if it's specified as an amount or percentage.
     */
    -(NSDecimalNumber* _Nullable)discountAmountForDisplay;

    /**
     * check if an item is equal to this
     */
    -(BOOL)isEqualToItem:(PPRetailInvoiceItem* _Nullable)item;




@end
