/**
 * PPRetailTransactionManager.h
 *
 * DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED AND SHOULD NOT BE CHECKED IN.
 * Generated from: js/transaction/TransactionManager.js
 *
 * 
 */

#import "PayPalRetailSDKTypeDefs.h"
#import "PPRetailObject.h"


@class PPRetailSDK;
@class PPRetailError;
@class PPRetailPayPalErrorInfo;
@class PPRetailAccountSummary;
@class PPRetailAccountSummarySection;
@class PPRetailInvoiceAddress;
@class PPRetailInvoiceAttachment;
@class PPRetailInvoiceBillingInfo;
@class PPRetailInvoiceCCInfo;
@class PPRetailCountries;
@class PPRetailCountry;
@class PPRetailInvoiceCustomAmount;
@class PPRetailInvoice;
@class PPRetailInvoiceActions;
@class PPRetailInvoiceConstants;
@class PPRetailInvoiceListRequest;
@class PPRetailInvoiceListResponse;
@class PPRetailInvoiceMetaData;
@class PPRetailInvoiceTemplatesResponse;
@class PPRetailInvoicingService;
@class PPRetailInvoiceItem;
@class PPRetailInvoiceMerchantInfo;
@class PPRetailInvoiceNotification;
@class PPRetailInvoicePayment;
@class PPRetailInvoicePaymentTerm;
@class PPRetailInvoiceRefund;
@class PPRetailInvoiceSearchRequest;
@class PPRetailInvoiceShippingInfo;
@class PPRetailInvoiceTemplate;
@class PPRetailInvoiceTemplateSettings;
@class PPRetailMerchant;
@class PPRetailNetworkRequest;
@class PPRetailNetworkResponse;
@class PPRetailSdkEnvironmentInfo;
@class PPRetailRetailInvoice;
@class PPRetailRetailInvoicePayment;
@class PPRetailTokenExpirationHandler;
@class PPRetailCaptureHandler;
@class PPRetailTransactionContext;
@class PPRetailTransactionManager;
@class PPRetailTransactionBeginOptions;
@class PPRetailReceiptDestination;
@class PPRetailDeviceManager;
@class PPRetailSignatureReceiver;
@class PPRetailReceiptOptionsViewContent;
@class PPRetailReceiptEmailEntryViewContent;
@class PPRetailReceiptSMSEntryViewContent;
@class PPRetailReceiptViewContent;
@class PPRetailCard;
@class PPRetailBatteryInfo;
@class PPRetailMagneticCard;
@class PPRetailPaymentDevice;
@class PPRetailManuallyEnteredCard;
@class PPRetailDeviceUpdate;
@class PPRetailCardInsertedHandler;
@class PPRetailDeviceStatus;
@class PPRetailPayer;
@class PPRetailTransactionRecord;
@class PPRetailAuthorizedTransaction;
@class PPRetailPage;
@class PPRetailDiscoveredCardReader;
@class PPRetailCardReaderScanAndDiscoverOptions;
@class PPRetailDeviceConnectorOptions;


/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/
/**
 * TransactionManager is a public facing facade to everything related to a Transaction.
 */
@interface PPRetailTransactionManager : PPRetailObject






    /**
     * Create a transaction using the provided Invoice. An existing transaction will be canceled
     */
    -(void)createTransaction:(PPRetailInvoice* _Nullable)invoice callback:(PPRetailTransactionManagerTransactionHandler _Nullable)callback;

    /**
     * Create a refund transaction. An existing transaction will be canceled
     */
    -(void)createRefundTransaction:(NSString* _Nullable)invoiceId transactionNumber:(NSString* _Nullable)transactionNumber paymentMethod:(PPRetailInvoicePaymentMethod)paymentMethod callback:(PPRetailTransactionManagerTransactionHandler _Nullable)callback;

    /**
     * Retrieve the list of authorized transactions.
     */
    -(void)retrieveAuthorization:(NSDate* _Nullable)startDateTime endDateTime:(NSDate* _Nullable)endDateTime pageSize:(int)pageSize status:(NSArray* _Nullable)status callback:(PPRetailTransactionManagerRetrieveAuthorizedTransactionsHandler _Nullable)callback;

    /**
     * Retrieve the next list of authorized transactions using the nextPageToken.
     */
    -(void)retrieveAuthorizationUsingToken:(NSString* _Nullable)nextPageToken callback:(PPRetailTransactionManagerRetrieveAuthorizedTransactionsHandler _Nullable)callback;

    /**
     * Void an authorized transaction
     */
    -(void)voidAuthorization:(NSString* _Nullable)authorizationId callback:(PPRetailTransactionManagerVoidAuthorizationHandler _Nullable)callback;

    /**
     * Capture a previously authorized transaction.
     */
    -(void)captureAuthorization:(NSString* _Nullable)authorizationId invoiceId:(NSString* _Nullable)invoiceId totalAmount:(NSDecimalNumber* _Nullable)totalAmount gratuityAmount:(NSDecimalNumber* _Nullable)gratuityAmount currency:(NSString* _Nullable)currency callback:(PPRetailTransactionManagerCaptureAuthorizedTransactionHandler _Nullable)callback;

    /**
     * Capture a previously authorized transaction.
     */
    -(void)captureAuthorization:(NSString* _Nullable)authorizationId invoiceId:(NSString* _Nullable)invoiceId totalAmount:(NSDecimalNumber* _Nullable)totalAmount gratuityAmount:(NSDecimalNumber* _Nullable)gratuityAmount currency:(NSString* _Nullable)currency base64SignatureJpeg:(NSString* _Nullable)base64SignatureJpeg callback:(PPRetailTransactionManagerCaptureAuthorizedTransactionHandler _Nullable)callback;




@end
