/**
 * PPRetailError.h
 *
 * DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED AND SHOULD NOT BE CHECKED IN.
 * Generated from: node_modules/@paypalcorp/manticore-paypalerror/src/PayPalError.js
 *
 * 
 */

#import "PayPalRetailSDKTypeDefs.h"
#import "PPRetailObject.h"


@class PPRetailSDK;
@class PPRetailError;
@class PPRetailPayPalErrorInfo;
@class PPRetailAccountSummary;
@class PPRetailAccountSummarySection;
@class PPRetailInvoiceAddress;
@class PPRetailInvoiceAttachment;
@class PPRetailInvoiceBillingInfo;
@class PPRetailInvoiceCCInfo;
@class PPRetailCountries;
@class PPRetailCountry;
@class PPRetailInvoiceCustomAmount;
@class PPRetailInvoice;
@class PPRetailInvoiceActions;
@class PPRetailInvoiceConstants;
@class PPRetailInvoiceListRequest;
@class PPRetailInvoiceListResponse;
@class PPRetailInvoiceMetaData;
@class PPRetailInvoiceTemplatesResponse;
@class PPRetailInvoicingService;
@class PPRetailInvoiceItem;
@class PPRetailInvoiceMerchantInfo;
@class PPRetailInvoiceNotification;
@class PPRetailInvoicePayment;
@class PPRetailInvoicePaymentTerm;
@class PPRetailInvoiceRefund;
@class PPRetailInvoiceSearchRequest;
@class PPRetailInvoiceShippingInfo;
@class PPRetailInvoiceTemplate;
@class PPRetailInvoiceTemplateSettings;
@class PPRetailMerchant;
@class PPRetailNetworkRequest;
@class PPRetailNetworkResponse;
@class PPRetailSdkEnvironmentInfo;
@class PPRetailRetailInvoice;
@class PPRetailRetailInvoicePayment;
@class PPRetailBraintreeManager;
@class PPRetailSimulationManager;
@class PPRetailMerchantManager;
@class PPRetailCaptureHandler;
@class PPRetailRecord;
@class PPRetailTransactionContext;
@class PPRetailTransactionManager;
@class PPRetailTransactionBeginOptions;
@class PPRetailReceiptDestination;
@class PPRetailDeviceManager;
@class PPRetailSignatureReceiver;
@class PPRetailReceiptOptionsViewContent;
@class PPRetailReceiptEmailEntryViewContent;
@class PPRetailReceiptSMSEntryViewContent;
@class PPRetailReceiptViewContent;
@class PPRetailOfflinePaymentStatus;
@class PPRetailOfflinePaymentInfo;
@class PPRetailOfflineTransactionRecord;
@class PPRetailQRCRecord;
@class PPRetailTokenExpirationHandler;
@class PPRetailCard;
@class PPRetailBatteryInfo;
@class PPRetailMagneticCard;
@class PPRetailDigitalCard;
@class PPRetailPaymentDevice;
@class PPRetailManuallyEnteredCard;
@class PPRetailDeviceUpdate;
@class PPRetailCardInsertedHandler;
@class PPRetailDeviceStatus;
@class PPRetailPayer;
@class PPRetailDigitalCardInfo;
@class PPRetailTransactionRecord;
@class PPRetailVaultRecord;
@class PPRetailAuthorizedTransaction;
@class PPRetailPage;
@class PPRetailDiscoveredCardReader;
@class PPRetailCardReaderScanAndDiscoverOptions;
@class PPRetailDeviceConnectorOptions;
@class PPRetailReaderConfiguration;
@class PPRetailSimulationOptions;

/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/
/**
 * A common base class for PayPal related errors which includes a debugId and code.
 * This id will be filled out if the error was generated from the PayPal servers.
 */
@interface PPRetailError : PPRetailObject
/**
 * The subsystem responsible for this error, in which the code
 * should uniquely identify the type of error that has occurred
 */
@property (nonatomic,strong,nullable) NSString* domain;/**
 * A non-localized code for this error
 */
@property (nonatomic,strong,nullable) NSString* code;/**
 * The explanation of the error
 */
@property (nonatomic,strong,nullable) NSString* message;/**
 * A server-generated identifier used by PayPal to help diagnose the error
 */
@property (nonatomic,strong,nullable) NSString* debugId;/**
 * A developer & user unfriendly message giving details about the error
 */
@property (nonatomic,strong,nullable) NSString* developerMessage;

- (instancetype _Nullable)init;
    


/**
 * Decorate an error to include code, domain and a localized message
 */
+(PPRetailError* _Nullable)makeError:(PPRetailError* _Nullable)error info:(PPRetailPayPalErrorInfo* _Nullable)info;



/**
 * Equality comparison
 */
-(BOOL)equals:(PPRetailError* _Nullable)paypalError;

/**
 * Get boolean value or default boolean value
 */
-(BOOL)getValue:(NSString* _Nullable)key defaultBool:(BOOL)defaultBool;

/**
 * Get string value or default string value
 */
-(NSString* _Nullable)getValue:(NSString* _Nullable)key defaultString:(NSString* _Nullable)defaultString;

/**
 * Get int value or default int value
 */
-(int)getValue:(NSString* _Nullable)key defaultInt:(int)defaultInt;

/**
 * Get decimal value or default decimal value
 */
-(NSDecimalNumber* _Nullable)getValue:(NSString* _Nullable)key defaultDecimal:(NSDecimalNumber* _Nullable)defaultDecimal;




@end
