/**
 * PPRetailOfflinePaymentStatus.h
 *
 * DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED AND SHOULD NOT BE CHECKED IN.
 * Generated from: js/transaction/OfflinePaymentStatus.js
 *
 * 
 */

#import "PayPalRetailSDKTypeDefs.h"
#import "PPRetailObject.h"


@class PPRetailSDK;
@class PPRetailError;
@class PPRetailPayPalErrorInfo;
@class PPRetailAccountSummary;
@class PPRetailAccountSummarySection;
@class PPRetailInvoiceAddress;
@class PPRetailInvoiceAttachment;
@class PPRetailInvoiceBillingInfo;
@class PPRetailInvoiceCCInfo;
@class PPRetailCountries;
@class PPRetailCountry;
@class PPRetailInvoiceCustomAmount;
@class PPRetailInvoice;
@class PPRetailInvoiceActions;
@class PPRetailInvoiceConstants;
@class PPRetailInvoiceListRequest;
@class PPRetailInvoiceListResponse;
@class PPRetailInvoiceMetaData;
@class PPRetailInvoiceTemplatesResponse;
@class PPRetailInvoicingService;
@class PPRetailInvoiceItem;
@class PPRetailInvoiceMerchantInfo;
@class PPRetailInvoiceNotification;
@class PPRetailInvoicePayment;
@class PPRetailInvoicePaymentTerm;
@class PPRetailInvoiceRefund;
@class PPRetailInvoiceSearchRequest;
@class PPRetailInvoiceShippingInfo;
@class PPRetailInvoiceTemplate;
@class PPRetailInvoiceTemplateSettings;
@class PPRetailMerchant;
@class PPRetailNetworkRequest;
@class PPRetailNetworkResponse;
@class PPRetailSdkEnvironmentInfo;
@class PPRetailRetailInvoice;
@class PPRetailRetailInvoicePayment;
@class PPRetailBraintreeManager;
@class PPRetailSimulationManager;
@class PPRetailMerchantManager;
@class PPRetailCaptureHandler;
@class PPRetailRecord;
@class PPRetailTransactionContext;
@class PPRetailTransactionManager;
@class PPRetailTransactionBeginOptions;
@class PPRetailReceiptDestination;
@class PPRetailDeviceManager;
@class PPRetailSignatureReceiver;
@class PPRetailReceiptOptionsViewContent;
@class PPRetailReceiptEmailEntryViewContent;
@class PPRetailReceiptSMSEntryViewContent;
@class PPRetailReceiptViewContent;
@class PPRetailOfflinePaymentStatus;
@class PPRetailOfflinePaymentInfo;
@class PPRetailOfflineTransactionRecord;
@class PPRetailQRCRecord;
@class PPRetailTokenExpirationHandler;
@class PPRetailCard;
@class PPRetailBatteryInfo;
@class PPRetailMagneticCard;
@class PPRetailDigitalCard;
@class PPRetailPaymentDevice;
@class PPRetailManuallyEnteredCard;
@class PPRetailDeviceUpdate;
@class PPRetailCardInsertedHandler;
@class PPRetailDeviceStatus;
@class PPRetailPayer;
@class PPRetailDigitalCardInfo;
@class PPRetailTransactionRecord;
@class PPRetailVaultRecord;
@class PPRetailAuthorizedTransaction;
@class PPRetailPage;
@class PPRetailDiscoveredCardReader;
@class PPRetailCardReaderScanAndDiscoverOptions;
@class PPRetailDeviceConnectorOptions;
@class PPRetailReaderConfiguration;
@class PPRetailSimulationOptions;

/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/
/**
 * OfflinePaymentStatus provides the status info for a given offline payment transaction
 */
@interface PPRetailOfflinePaymentStatus : PPRetailObject
/**
 * the id of the offline txn @readonly
 */
@property (nonatomic,strong,nullable,readonly) NSString* id;/**
 * Show the create time of the offline txn @readonly
 */
@property (nonatomic,strong,nullable,readonly) NSDate* createTime;/**
 * the total amount of the offline txn @readonly
 */
@property (nonatomic,strong,nullable,readonly) NSDecimalNumber* amount;/**
 * the card issuer of the card used for the txn @readonly
 */
@property (nonatomic,strong,nullable,readonly) NSArray* cardIssuer;/**
 * the retry counter of the offline txn @readonly
 */
@property (nonatomic,assign,readonly) int retry;/**
 * the replay counter of the offline txn @readonly
 */
@property (nonatomic,assign,readonly) int replay;/**
 * the error no of the offline txn after replaying it @readonly
 */
@property (nonatomic,assign,readonly) int errNo;/**
 * the error message of the offline txn after replaying if failed @readonly
 */
@property (nonatomic,strong,nullable,readonly) NSString* errMessage;/**
 * the flag showing if the txn is declined during replay @readonly
 */
@property (nonatomic,assign,readonly) BOOL isDeclined;/**
 * Show the expiry time of the offline txn @readonly
 */
@property (nonatomic,strong,nullable,readonly) NSDate* expiry;/**
 * of this transaction @readonly
 */
@property (nonatomic,assign,readonly) PPRetailOfflineTransactionState state;/**
 * The invoice number of the offline tx @readonly
 */
@property (nonatomic,strong,nullable,readonly) NSString* invoiceNumber;/**
 * The invoice id of the offline tx @readonly
 */
@property (nonatomic,strong,nullable,readonly) NSString* invoiceId;/**
 * The transaction number of the offline tx @readonly
 */
@property (nonatomic,strong,nullable,readonly) NSString* transactionNumber;/**
 * The latitude of the offline tx @readonly
 */
@property (nonatomic,strong,nullable,readonly) NSString* latitude;/**
 * The longitude of the offline tx @readonly
 */
@property (nonatomic,strong,nullable,readonly) NSString* longitude;/**
 * of the offline tx @readonly
 */
@property (nonatomic,assign,readonly) PPRetailTransactionBeginOptionsPaymentTypes paymentType;/**
 * card details of the card used for the offline tx @readonly
 */
@property (nonatomic,strong,nullable,readonly) PPRetailCard* card;/**
 * The invoice of the offline tx @readonly
 */
@property (nonatomic,strong,nullable,readonly) PPRetailRetailInvoice* invoice;

- (instancetype _Nullable)init;
    







@end
