/**
 * PPRetailRetailInvoice.h
 *
 * DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED AND SHOULD NOT BE CHECKED IN.
 * Generated from: js/common/invoicing/RetailInvoice.js
 *
 * 
 */

#import "PayPalRetailSDKTypeDefs.h"
#import "PPRetailObject.h"
#import "PPRetailInvoice.h"

@class PPRetailSDK;
@class PPRetailError;
@class PPRetailPayPalErrorInfo;
@class PPRetailAccountSummary;
@class PPRetailAccountSummarySection;
@class PPRetailInvoiceAddress;
@class PPRetailInvoiceAttachment;
@class PPRetailInvoiceBillingInfo;
@class PPRetailInvoiceCCInfo;
@class PPRetailCountries;
@class PPRetailCountry;
@class PPRetailInvoiceCustomAmount;

@class PPRetailInvoiceActions;
@class PPRetailInvoiceConstants;
@class PPRetailInvoiceListRequest;
@class PPRetailInvoiceListResponse;
@class PPRetailInvoiceMetaData;
@class PPRetailInvoiceTemplatesResponse;
@class PPRetailInvoicingService;
@class PPRetailInvoiceItem;
@class PPRetailInvoiceMerchantInfo;
@class PPRetailInvoiceNotification;
@class PPRetailInvoicePayment;
@class PPRetailInvoicePaymentTerm;
@class PPRetailInvoiceRefund;
@class PPRetailInvoiceSearchRequest;
@class PPRetailInvoiceShippingInfo;
@class PPRetailInvoiceTemplate;
@class PPRetailInvoiceTemplateSettings;
@class PPRetailMerchant;
@class PPRetailNetworkRequest;
@class PPRetailNetworkResponse;
@class PPRetailSdkEnvironmentInfo;
@class PPRetailRetailInvoice;
@class PPRetailRetailInvoicePayment;
@class PPRetailBraintreeManager;
@class PPRetailSimulationManager;
@class PPRetailMerchantManager;
@class PPRetailCaptureHandler;
@class PPRetailRecord;
@class PPRetailTransactionContext;
@class PPRetailTransactionManager;
@class PPRetailTransactionBeginOptions;
@class PPRetailReceiptDestination;
@class PPRetailDeviceManager;
@class PPRetailSignatureReceiver;
@class PPRetailReceiptOptionsViewContent;
@class PPRetailReceiptEmailEntryViewContent;
@class PPRetailReceiptSMSEntryViewContent;
@class PPRetailReceiptViewContent;
@class PPRetailOfflinePaymentStatus;
@class PPRetailOfflinePaymentInfo;
@class PPRetailOfflineTransactionRecord;
@class PPRetailQRCRecord;
@class PPRetailTokenExpirationHandler;
@class PPRetailCard;
@class PPRetailBatteryInfo;
@class PPRetailMagneticCard;
@class PPRetailDigitalCard;
@class PPRetailPaymentDevice;
@class PPRetailManuallyEnteredCard;
@class PPRetailDeviceUpdate;
@class PPRetailCardInsertedHandler;
@class PPRetailDeviceStatus;
@class PPRetailPayer;
@class PPRetailDigitalCardInfo;
@class PPRetailTransactionRecord;
@class PPRetailVaultRecord;
@class PPRetailAuthorizedTransaction;
@class PPRetailPage;
@class PPRetailDiscoveredCardReader;
@class PPRetailCardReaderScanAndDiscoverOptions;
@class PPRetailDeviceConnectorOptions;
@class PPRetailReaderConfiguration;
@class PPRetailSimulationOptions;

/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/
/**
 * The "Retail" Implementation of Invoice that is used by PPH only. Contains receiptDetails such as store ID,
 * TerminalID, and countryCode.
 * This class is a specific version implementation of the Invoice.
 */
@interface PPRetailRetailInvoice : PPRetailInvoice
/**
 * Transaction type of the Invoice
 */
@property (nonatomic,strong,nullable) NSString* name;/**
 * Total Invoice amount
 */
@property (nonatomic,strong,nullable) NSDecimalNumber* total;/**
 * The transaction handle
 */
@property (nonatomic,strong,nullable) NSString* txnHandle;/**
 * The country object that contains the country code and country name
 */
@property (nonatomic,strong,nullable) NSString* countryCode;/**
 * The store id where the receipt was generated
 */
@property (nonatomic,strong,nullable) NSString* storeId;/**
 * The terminal ID where the actual receipt was generated
 */
@property (nonatomic,strong,nullable) NSString* terminalId;/**
 * The seller Id (Normally set to Primary users' full name)
 */
@property (nonatomic,strong,nullable) NSString* sellerId;/**
 * The current status of the invoice
 */
@property (nonatomic,assign) PPRetailInvoiceStatus status;/**
 * an array of payment objects
 */
@property (nonatomic,strong,nullable) NSArray* payments;/**
 * The device name
 */
@property (nonatomic,strong,nullable) NSString* deviceName;/**
 * The custom footer text
 */
@property (nonatomic,strong,nullable) NSString* footer;/**
 * The id assigned by PayPal for an invoice. This is basically same the
 * super class' payPalId. This is added to open the setter on the native side.
 */
@property (nonatomic,strong,nullable) NSString* payPalId;/**
 * Check if the transaction was cancelled by the user
 */
@property (nonatomic,assign) BOOL isCancelled;/**
 * Check if the payment was declined by the api
 */
@property (nonatomic,assign) BOOL isFailed;/**
 * the referrer code coming from sideloader calls
 */
@property (nonatomic,strong,nullable) NSString* referrerCode;

- (instancetype _Nullable)initWithCurrencyCode:(NSString* _Nullable)currencyCode;
    - (instancetype _Nullable)init NS_UNAVAILABLE;
+ (instancetype _Nullable)new NS_UNAVAILABLE;




/**
 * Create a true copy / duplicate of an invoice. This is named duplicate instead
 * of copy to avoid code gen issues on iOS
 */
-(PPRetailRetailInvoice* _Nullable)duplicate;




@end
